### PR TITLE
[ReadyToUse] Rogue Outlaw Dragonflight Pre-patch

### PR DESCRIPTION
**Pull request by IIeTpoc**
I fixed Talents' IDs and tried to implement existing logic from rogue Shadowlands to Dragonflight. I fixed some values from the abbilities i am confident about as I was checking in retail. Talents and logic i was not familliar with i just left as it is.
APL is taken from the lates Simc nightly build and adapted to the lua and as far as i can see it is pretty much the same it was during 9.2.7 http://downloads.simulationcraft.org/nightly/simc-920.01.948f6a8-win64.7z

Revising is very needed in

Talent "deeper_strategem_2" as the talent ID was changed and renamed on retail https://www.wowhead.com/spell=394321/devious-stratagem
Dreadblades now gives combo_points.max upon use the spell and cost 50 energy https://www.wowhead.com/spell=343142/dreadblades
I do not know how to implement charges to Opportunity buff from https://www.wowhead.com/spell=381846/fan-the-hammer and how to implement these changes to Pistol shot

### CODE REVIEW

**Comment by IIeTpoc** [comment]
@Hekili I updated talents' IDs and now it is actually working in terms of abbility detection. 

As of **Beta v9** the problem I am encountering now is that it wants to recast Flagelation when it should be already on cooldown and allows me to snapshot only after LUA error.
(how to reproduce - meet Flagellation requirements and use it, then addon just hangs for 5 seconds or untill i disable cooldowns and gives then following LUA errors)

LUA error i get:
https://pastebin.com/LMdQkkmU

This LUA error i get after reloading as 1st LUA error
https://pastebin.com/k7jJrQip

This LUA error i get as a subsequent when it fails to instantly snapshot
https://pastebin.com/3FLgJ63s

Snapshot after disabling/enabling CDs when i used flagellation
https://pastebin.com/5dJjZUy6

Also as a side problem, addon reccomends me to Use Slice and Dice in precombat ((as 2nd of 3d abbility after Stealth and Roll the Bones, both of which do not give Combo Points), but it is impossible as i do not have Combo Points. This false recommendation disappears after i enter combat,
Snapshot of this reccomendation (as 2nd of 3d abbility):
https://pastebin.com/QXz4bn8d

**Comment by IIeTpoc** [comment]
@Hekili
Hi! I think I reached my peak of knowledge here. Thank you again for your work, your addon is really awesome and helps people actually enjoy the game.

To do list:
1. Fix Flagellation: (Major bug which freezes recommendations untill flagellation_buff expires, basicly it does not detect duration of buff.flagellation_buff,expires)

v10.0.0.1 
error: https://pastebin.com/6uduUHBk
snapshot: https://pastebin.com/DF8CYj1v

2. Fix  Echoing Reprimand detection spell 

https://pastebin.com/uS25jxek

3. Slice and Dice recommended at precombat with no combat points

Snapshot of this reccomendation (as 2nd of 3d abbility after spells that do not grant CP):
https://pastebin.com/QXz4bn8d

4. Implement buffs: take_em_by_surprise, thistle_tea,  shallow_insight, moderate_insight from talents 

Apart from this no major bugs detected. APL imports aswell, no FPS dropps detected

**Comment by IIeTpoc** [comment]
Outlaw is now ready to use without any errors. 
I was focusing on supporting the following talent choices

Solo: BQQAAAAAAAAAAAAAAAAAAAAAAAAAABJBkkkQSLRgEIRiEAJCAAAAAAQSQaUSCSSSKBAAAA
AOE: BQQAOB/7AZ//CwQOf4fPMswHVDAAABJJAJJRSLJJQgEJSAkIAAAAAAAJBpRJJIJJpFAAAA

**Comment by T0xicsmog** [comment]
Please remember, if you happen to install this into your files, THIS IS NOT A HEKILI RELEASE AND DOES NOT HAVE ISSUE SUPPORT SO DO NOT REPORT ANY TICKETS.

**Comment by baruchvlz** [comment]
~~Been using this for the past few dungeons, unfortunately it's not recommending Flagellation at all. (Not sure how important this is considering it's a SL talent, but figured I'd mention it.)~~

It's working now 🤷

**Comment by T0xicsmog** [comment]
Been working fine for me, you may have Imported it incorrectly

**Comment by vond82** [comment]
I gave this a go in a key to try it out, and had no issues with Flagellation tbh. What I did find was that Pistol Shot would be constantly recommended during Dreadblades, when it should be exactly the opposite. It was recommended with and without Opportunity procs. There were some other minor things I noticed as well but haven't had time to look thru the .simc file yet, just figured I'd mention this

**Comment by T0xicsmog** [comment]
> I gave this a go in a key to try it out, and had no issues with Flagellation tbh. What I did find was that Pistol Shot would be constantly recommended during Dreadblades, when it should be exactly the opposite. It was recommended with and without Opportunity procs. There were some other minor things I noticed as well but haven't had time to look thru the .simc file yet, just figured I'd mention this

my guess would be it has to do with the way pistol shot update [663d8b7](https://github.com/Hekili/hekili/pull/1727/commits/663d8b7b6b6e4e8b2045524fefd64e53f2c132be) was written to include the fan the hammer optimizations, im no coder though

**Comment by IIeTpoc** [comment]
> my guess would be it has to do with the way pistol shot update [663d8b7](https://github.com/Hekili/hekili/pull/1727/commits/663d8b7b6b6e4e8b2045524fefd64e53f2c132be) was written to include the fan the hammer optimizations, im no coder though

It is exactly this update [663d8b7](https://github.com/Hekili/hekili/pull/1727/commits/663d8b7b6b6e4e8b2045524fefd64e53f2c132be) and i tried to code in following rule i found from Foreverguy on Ravenhold rogue discorde

> Fan the Hammer optimization rules were found. While you still tend to consume Opportunity procs as you get them, there are moments where you can skip them:
      - Skip Opportunity procs if you are below 6 stacks during Dreadblades.
      - Skip Opportunity procs if you are below 6 stacks and at 4 or more CP.
You still follow these rules even if Greenskins is active. Ignore these rules if Opportunity is about to expire.

**Comment by Paua-Hua** [comment]
How do i input the version with all the fixes?

**Comment by IIeTpoc** [comment]
> How do i input the version with all the fixes?

Look at [changes in the files](https://github.com/Hekili/hekili/pull/1727/files) and do the same in your addon folder

**Comment by T0xicsmog** [comment]
> > my guess would be it has to do with the way pistol shot update [663d8b7](https://github.com/Hekili/hekili/pull/1727/commits/663d8b7b6b6e4e8b2045524fefd64e53f2c132be) was written to include the fan the hammer optimizations, im no coder though
> 
> It is exactly this update [663d8b7](https://github.com/Hekili/hekili/pull/1727/commits/663d8b7b6b6e4e8b2045524fefd64e53f2c132be) and i tried to code in following rule i found from Foreverguy on Ravenhold rogue discorde
> 
> > Fan the Hammer optimization rules were found. While you still tend to consume Opportunity procs as you get them, there are moments where you can skip them:
> > - Skip Opportunity procs if you are below 6 stacks during Dreadblades.
> > - Skip Opportunity procs if you are below 6 stacks and at 4 or more CP.
> > You still follow these rules even if Greenskins is active. Ignore these rules if Opportunity is about to expire.

so my guess is the coding language is probably backwards in this somewhere

**Comment by IIeTpoc** [comment]
Wow they recently made an APL for simcraft. I might look at it when i have time and update this unless someone wants to do that aswell)
https://github.com/simulationcraft/simc/blob/4301b5ff1c522fab035cf4974378ef2b7fdd77c9/engine/class_modules/apl/rogue/outlaw_df.simc

**Comment by Paua-Hua** [comment]
> > How do i input the version with all the fixes?
> 
> Look at [changes in the files](https://github.com/Hekili/hekili/pull/1727/files) and do the same in your addon folder

Thanks! bit confused will give it a crack appreciate your work

**Comment by Klownmechanics** [comment]
hey just a question when im coping the new files do i copy and paste the hole log into my rogue (outlaw) hekili addon folder

**Comment by Sedveth** [comment]
Thank you for your work. After testing for few minutes, there are a lot of errors with this build. Like we do not consume Opp proc at 4 or more Combo Point if FTH stack = 3, we should just keep doing sinister strike, or in Dreadblades window, we don't wanna reroll RTB. And since this build do not support Echo Reprimand, it also didn't detect Empower Combo Point to send a finisher.

**Comment by Triplehxh** [comment]
i copied your modified files into my hekili folders and was able to get hekili  visible again. During the dungeon i recognized that for me sinister strike was not visible onces. Shiv was the whole time visible as 2nd or 3rd attack. And after 10 seconds of fight its starts hanging. 1 Attack was go into stealth (but i was still infight). 

On a dummy the rotation was working fine but Echoing Reprimand was not visible at all.

**Comment by aohajin** [comment]
This one is awesome.

Actually I got my first mythic raid boss 100% ranking on WCL with your pr.

image

Great work!

**Comment by Triplehxh** [comment]
Without Echoing Reprimand its running really smooth now!

**Comment by PhoenixMariie** [comment]
> Without Echoing Reprimand its running really smooth now!

How do I get it working more or less for rogue before Mr. Lord Hekili is done?

**Comment by Triplehxh** [comment]
Go here under this topic under Top right to Files Changed and you will find these 4 files

image

For each file click on the 3 dots next to "Viewed" and then"View File" Replace the content you see in this files with the files in your addons folder

**Comment by PhoenixMariie** [comment]
> Go here under this topic under Top right to Files Changed and you will find these 4 files
> 
> image
> 
> For each file click on the 3 dots next to "Viewed" and then"View File" Replace the content you see in this files with the files in your addons folder

Thanks. Couldnt find the "RogueOutlaw.simc" in APLs folder though. Might just wait for our lord and savoir to be done :)

**Comment by AlanCiantarISL** [comment]
> > Go here under this topic under Top right to Files Changed and you will find these 4 files
> > image
> > For each file click on the 3 dots next to "Viewed" and then"View File" Replace the content you see in this files with the files in your addons folder
> 
> Thanks. Couldnt find the "RogueOutlaw.simc" in APLs folder though. Might just wait for our lord and savoir to be done :)

It's a new file my guy - create it :)

**Comment by baruchvlz** [comment]
Best way to get this to work is to:

1. [Click here](https://github.com/IIeTpoc/hekili/tree/IIeTpoc-patch-2) to @IIeTpoc repository
2. Click on the green `Code` button to open the dropdown
3. Click on `Download ZIP`
5. Go to the Hekili folder (default installation is here:  `C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Hekili`)
6. Move the downloaded files and folder to the Hekili folder

Repeat these steps every time a new change happens on this pull request.

image

**DIRECT DOWNLOAD LINK:** https://github.com/IIeTpoc/hekili/archive/refs/heads/IIeTpoc-patch-2.zip

**Comment by T0xicsmog** [comment]
> Best way to get this to work is to:
> 
> 1. [Click here](https://github.com/IIeTpoc/hekili/tree/IIeTpoc-patch-2) to @IIeTpoc repository
> 2. Click on the green `Code` button to open the dropdown
> 3. Click on `Download ZIP`
> 4. Go to the Hekili folder (default installation is here:  `C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Hekili`)
> 5. Move the downloaded files and folder to the Hekili folder
> 
> Repeat these steps every time a new change happens on this pull request.
> 
> image
> 
> **DIRECT DOWNLOAD LINK:** https://github.com/IIeTpoc/hekili/archive/refs/heads/IIeTpoc-patch-2.zip

Please remember that this is made by someone who loves the addon. !!!DO NOT SUBMIT BUG FIXES TO HEKILI!!!

**Comment by Hekili** [comment]
What's the reason for the changes in Covenants.lua?

**Comment by IIeTpoc** [comment]
> What's the reason for the changes in Covenants.lua?

@Hekili It is the same as in #1753 . Without it Flagellation buff duration can not be calculated and addond hangs

That is what exactly was changed in Covenants.lua

https://github.com/Hekili/hekili/pull/1727/commits/2b1511057df7cb5a6d8cf6aa190d6eda3cbfe0eb

**Comment by ravisangha** [comment]
Hey I was hoping I could get some help getting the outlaw code to work. I'm not too technically inclined but I followed the simple instruction above and wanted to confirm I had done everything correctly and this is how my Hekili folder looks now, however addon is still not available while playing my rogue. Any help would be appreciated. Thanks!
image

**Comment by ravisangha** [comment]
Just wanted to say thanks I sort of can't play outlaw without some help and was pretty bummed that the OL code hadn't been updated. Thanks again!

**Comment by Hekili** [comment]
@IIeTpoc Are there unresolved differences between your work and what is available in the current release?

**Comment by IIeTpoc** [comment]
> @IIeTpoc Are there unresolved differences between your work and what is available in the current release?

@Hekili Hey! I don't think so! Will check it out when i get to WoW next week. Thank you very much for the Outlaw update!

**Pull request closed without merging**
