### PR TITLE
Update AzE to Cov

### PR DESCRIPTION
**Pull request by ChrisKader**

### CODE REVIEW

**Comment by ChrisKader** [comment]
Minimap Button Tooltip before change:
image

**Comment by Hekili** [comment]
Well, this is kinda funny.  The tooltip *is* wrong, but it's not there to say AOE.  It was shorthand for Azeroth Essences (from BfA), and should now be updated to reflect it's used for Covenant abilities.  So I'll change it, but it should really be "Cov" or some such.

**Comment by ChrisKader** [comment]
Well now I feel silly. I had see AzE for so long and assumed it was AoE and didn't even think about the fact that AoE would not even fit in the context of the other options.

**Comment by Hekili** [comment]
It's not that silly; the context for it being "Azerite Essences" is more than a year out of date.

**Review by Hekili — APPROVED** [review]

**Pull request merged**
