### PR TITLE
Feral max_energy fix

### LINKED ISSUE #869: Feral Druid Errors
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**

**To Reproduce**
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**

**Screenshots**

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**
3127x Hekili\Classes\DruidFeral.lua:1203: attempt to compare number with boolean
[string "@Hekili\Classes\DruidFeral.lua"]:1203: in function <Hekili\Classes\DruidFeral.lua:1201>
[string "=(tail call)"]: ?
[string "@Hekili\State.lua"]:6454: in function `TimeToReady'
[string "@Hekili\Core.lua"]:751: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:820: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1284: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1580: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:824: in function <Hekili\UI.lua:689>

### PR DESCRIPTION
**Pull request by ShmooDude**
#869 fix

### CODE REVIEW

**Comment by Hekili** [comment]
This is already in my code and in the commit from 3 days ago.  I'm very confused.

**Comment by Hekili** [comment]
What version of the addon are you using that doesn't already have this?

**Comment by Hekili** [comment]
@ShmooDude I can't replicate the error.  `args.max_energy` is a numeric value and that comparison works as-is in my code.  I need debug information that's missing from the ticket.  Can you provide character information so I can try to replicate on my end?

**Comment by ShmooDude** [comment]
`args.max_energy` was either `nil` or `true` when I did a `print()` on it, so it definitely wasn't numeric:

94x Hekili\Classes\DruidFeral.lua:1203: **attempt to compare number with boolean**
[string "@Hekili\Classes\DruidFeral.lua"]:1203: in function <Hekili\Classes\DruidFeral.lua:1201>
[string "=(tail call)"]: ?
[string "@Hekili\State.lua"]:6454: in function `TimeToReady'
[string "@Hekili\Core.lua"]:751: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:820: in function `GetPredictionFromAPL'
[string "@Hekili\Core.lua"]:1284: in function `GetNextPrediction'
[string "@Hekili\Core.lua"]:1629: in function `ProcessHooks'
[string "@Hekili\UI.lua"]:824: in function <Hekili\UI.lua:689>

Locals:
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with boolean"

Character Information: 
build: v9.0.2-1.0.36a
level: 60 (60)
class: DRUID
spec: feral

talents: mighty_bash
    moment_of_clarity
    predator
    primal_wrath
    restoration_affinity
    soul_of_the_forest
    wild_charge

pvptalents: ferocious_wound
   fresh_wound
   leader_of_the_pack

covenant: night_fae

conduits: born_of_the_wilds = 6
   carnivorous_instinct = 5
   conflux_of_elements = 5
   wellhoned_instincts = 5

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   run_without_tiring = 1

sets: sinful_gladiators_badge_of_ferocity = 1
    sinful_gladiators_medallion = 1

gear: azurevenom_choker = 1
    chiropteran_leggings = 1
    cowled_batwing_cloak = 1
    girdle_of_shattered_dreams = 1
    miasmalacquered_jerkin = 1
    primeval_souls_ankleguards = 1
    quarterstaff_of_discordant_ethic = 1
    radiant_light_binders = 1
    seedtenders_handwraps = 1
    sinful_gladiators_badge_of_ferocity = 1
    sinful_gladiators_band = 1
    sinful_gladiators_leather_shoulderpads = 1
    sinful_gladiators_medallion = 1
    sinful_gladiators_signet = 1
    umbrahide_helm = 1

legendaries: circle_of_life_and_death = 1

itemIDs: 172317, 175921, 178373, 178381, 178442, 178805, 178847, 179352, 180097, 180115, 181333, 182993, 183009, 183034, 184172

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 3
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = ShmooDude Feral
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    owlweave_cat = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

EDIT: Snapshot won't even generate due to error.

**Comment by Hekili** [comment]
Is this based on a custom priority?  Because my import and toggle setup for max_energy is simply 1/0.  I'm wondering if you've implemented/shared something where max_energy is a conditional rather than just 1/0.

Something like:  `ferocious_bite,max_energy=1*buff.bs_inc.down`

I trawled your GitHub and imported your latest priorities/packs w/o issue on mine.

If you're using a custom priority, and you reimport your script, does it resolve?

Do you have ViragDevTool or VDT installed?

**Comment by ShmooDude** [comment]
Yeah, it was a custom priority.  I reimported the priority and now it works.

**Comment by Hekili** [comment]
I'll go ahead and babyproof it in case there are boolean `max_energy` lists out in the wild.

**Pull request closed without merging**
