### PR TITLE
Cleanup vesper totem

### PR DESCRIPTION
**Pull request by imarkvisser**
Removing vesper totem as it's not in the game anymore.

### CODE REVIEW

**Comment by syrifgit** [comment]
It's still available if you go to Shadowlands as a Kyrian. Normally Hekili likes to keep in support for legacy stuff (trust me, I always keep asking to delete it lmao), but maybe some of the advanced interactions could still be cut out while still leaving basic support for the ability?

You could also add some checks like I did recently to hunter and rogue which will reduce computation time when not doing legacy content.

`if covenant.kyrian then if now - action.resonating_arrow.lastCast < 6 then applyBuff( "resonating_arrow", 10 - ( now - action.resonating_arrow.lastCast ) ) end end`

covenant.X will always return false if you're not in Shadowlands zones, so saves resources.

It could also be possible to maybe even make a more global variable which updates on zone change, store it as `local shadowlandsLegacy` or something, `return covenant.X or covenant.Y or covenant.Z or covenant.W or false`, then gate all these things behind that.

**Comment by imarkvisser** [comment]
Whoops I was not aware it's still available in legacy content.

Are you sure we can use `covenant.kyrian`? Maybe we do extra checks in hekili but technically we still have active covenants;
image

Putting it behind a toggle is a good idea, maybe just checking if the spell is known.

**Comment by syrifgit** [comment]
> Whoops I was not aware it's still available in legacy content.
> 
> Are you sure we can use `covenant.kyrian`? Maybe we do extra checks in hekili but technically we still have active covenants; image
> 
> Putting it behind a toggle is a good idea, maybe just checking if the spell is known.

To check what Hekili sees for that, use 

```
/dump Hekili.State.covenant
/dump Hekili.State.covenant.necrolord
/dump Hekili.State.covenant.kyrian
/dump Hekili.State.covenant.venthyr
/dump Hekili.State.covenant.night_fae
```

My hunter in Dornogal
image


My hunter in shadowlands
image

I think the addon definition of covenant uses some spell checks too in order to come up with the answer.

```
    -- Check Covenant spells to disable them.
    local CovenantSpells = {
        [300728] = 1,
        [304971] = 1,
        [306830] = 1,
        [307443] = 1,
        [307865] = 1,
        [308491] = 1,
        [310454] = 1,
        [311648] = 1,
        [312202] = 1,
        [312321] = 1,
        [314791] = 1,
        [314793] = 1,
        [315443] = 1,
        [316958] = 1,
        [317009] = 1,
        [317485] = 1,
        [320674] = 1,
        [321792] = 1,
        [323546] = 1,
        [323547] = 1,
        [323639] = 1,
        [323654] = 1,
        [323673] = 1,
        [323764] = 1,
        [324128] = 1,
        [324143] = 1,
        [324149] = 1,
        [324220] = 1,
        [324386] = 1,
        [324631] = 1,
        [324724] = 1,
        [325013] = 1,
        [325020] = 1,
        [325028] = 1,
        [325216] = 1,
        [325283] = 1,
        [325289] = 1,
        [325640] = 1,
        [325886] = 1,
        [326059] = 1,
        [326434] = 1,
        [326647] = 1,
        [326860] = 1,
        [327104] = 1,
        [327661] = 1,
        [328204] = 1,
        [328231] = 1,
        [328281] = 1,
        [328282] = 1,
        [328305] = 1,
        [328547] = 1,
        [328620] = 1,
        [328622] = 1,
        [328923] = 1,
        [328930] = 1,
        [330325] = 1,
        [355589] = 1,
        [356532] = 1,
    }

    local IsCovenantSpell = function( spellID )
        return CovenantSpells[ spellID ] == 1
    end
    ns.IsCovenantSpell = IsCovenantSpell

    local covenantsDisabled = nil

    local AreCovenantsDisabled = function()
        if covenantsDisabled == nil then
            if FindStringInConduitTooltip( DisableText, 5, true, true ) then
                covenantsDisabled = true
                return true
            end
            covenantsDisabled = false
            return false
        end
        return covenantsDisabled
    end
    ns.AreCovenantsDisabled = AreCovenantsDisabled

    local IsDisabledCovenantSpell = function( spellID )
        return CovenantSpells[ spellID ] and AreCovenantsDisabled()
    end
    ns.IsDisabledCovenantSpell = IsDisabledCovenantSpell

    local WipeCovenantCache = function()
        covenantsDisabled = nil
    end
    ns.WipeCovenantCache = WipeCovenantCache
end
```

**Comment by syrifgit** [comment]
I'd actually be interested in seeing the output of that in a mists of tirna scithe key ...

**Comment by Hekili** [comment]
Covenant detection works for the appropriate settings.

**Pull request closed without merging**
