### PR TITLE
Rogue Conduit.nimble_fingers fix

### PR DESCRIPTION
**Pull request by IIeTpoc**
The logic behind "conduit.nimble_fingers" is to decrease the value (https://github.com/Hekili/hekili/blob/shadowlands/Shadowlands/SoulbindConduits.lua Line 247) so we get less energy spent. But here if we substract the already negative value we actually increase the energy cost of the spell. Here is a fix.

### CODE REVIEW

**Comment by IIeTpoc** [comment]
Also i updated Kidney shot for all specs

**Comment by IIeTpoc** [comment]
Also added animacharged_cp function update

**Review by Hekili — COMMENTED** [review]
Sorry, what is it you're intending to accomplish with this specific change?

**Review by Hekili — CHANGES_REQUESTED** [review]
The spend change is not necessary.

**Review by Hekili — CHANGES_REQUESTED** [review]
What is accomplished by changing 'animacharged_cp'?  What problem are you solving?  It isn't even used in any priorities.

**Comment by Hekili** [comment]
Thanks for catching the conduit issue and the info re: Kidney Shot; I've integrated those changes.  `animacharged_cp` is now removed.

**Pull request closed without merging**
