### PR TITLE
Target Count settings UI

### LINKED ISSUE #3945: [REC] MM Hunter - Wailing Arrow is not recommended
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Hunter - Marksmanship

### Describe the Issue

Wailing Arrow is not recommended by Hekili. 

With primary icon set to show three next actions, addon will show Trueshot and as next icon in queue Wailing Arrow. That is because Trueshot is set to apply wailing_arrow_override buff and Wailing Arrow require wailing_arrow_override to be suggested, but the moment you use Trueshot addon ignores Wailing Arrow 

in HunterMarksmanship.lua wailing_arrow_override has id 459808 - there is no buff/aura with that id when Wailing Arrow is usable (I've checked that using WeakAuras)

using WeakAuras I made simple wa to show when Wailing Arrow is usable 
trigger spell -> spell usable -> spell id 355589
WeakAura -> https://pastebin.com/Xp3rTrsg

### How to Reproduce

1. Enter game as MM Hunter
2. Use ST build from wowhead (Sentinel or Dark Ranger)
3. Follow normal rotation on ST dummy
4. it is most noticeable when addon suggest Trueshot, Wailing Arrow should be suggested as next ability right after Trueshot

### Snapshot (Link)

Snapshot taken right after Trueshot was used
https://pastebin.com/JJg4KCWg

### Raidbots Sim Report (Link)

_No response_

### Additional Information

_No response_

### Contact Information

_No response_

### LINKED ISSUE #3950: [REC] Destruction warlock doesn't use Cataclysm to refresh Immolate when available
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Destruction

### Describe the Issue

As per the Warlock priority (on Wowhead) and in the Simcraft APL (see included simc report) Destro is supposed to use Cataclysm even in single target to refresh Immolate over raw casting Immolate when possible.

### How to Reproduce

Play Destro lock in a single target scenario and need to refresh Immolate when Cataclsym is available.

### Snapshot (Link)

https://pastebin.com/xZzA7jmS

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/r8KxDHxRVhV9y6nDHXKY6w/simc

### Additional Information

_No response_

### Contact Information

_No response_

### LINKED ISSUE #3963: Infernal Bolt detection issue
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warlock - Destruction

### Describe the Issue

Recommendation issue when practicing on a target dummy.

Really nothing weird.

### How to Reproduce

See logfile.

### Snapshot (Link)

https://pastebin.com/BEVsYZy1

### Raidbots Sim Report (Link)

(https://www.raidbots.com/simbot/report/atm7Hhv2FfT4DKDtuf1JWe)
### Additional Information

_No response_

### Contact Information

_No response_

### PR DESCRIPTION
**Pull request by syrifgit**
### Marksmanship Hunter

- Wailing Arrow
  - Wailing arrow improvements. Could use polish regarding wind arrow stacking, but is now functional when it becomes usable. 
  - Solution to #3945 
 - Black Arrow
   - Properly apply deathblow and razor fragments when casting black arrow
   - Allows addon to predict killshot in the rotation

### Destruction  Warlock
- Stop the funnel toggle from blocking the single target part of the APL
- Stop Cataclysm from being assigned to the interrupt toggle in single target
  - It is a part of the regular rotation now, fixes #3950 
- Fix Infernal Bolt SpellID in the precast, it was checking the buffID not the spellID. Should fix #3963 

### Affliction Warlock
- Stop the funnel toggle from blocking the single target part of the APL

### Mage
- Shifting power should be on the CDs toggle by default. If CDs are turned off, recommending shifting power while your other CDs are available is not very good.

### General UI
- Update target settings UI to better guide the user through making their selections
- Separate pet-based detection from nameplate detection
- Change wording of many options
- Minor tweaks to size / order of options

Actual targeting logic has not been modified yet, that will be a future PR.

### CODE REVIEW

**Comment by syrifgit** [comment]
image
image
image
image
image

**Comment by Hekili** [comment]
Options should be title-cased consistently.

I also don't like "Allow addon to recommend Target Swaps" -- if the goal is to clarify Recommend *will* happen vs. Allow *to* happen, it can just be "Allow Target Swaps".

**Comment by syrifgit** [comment]
More UI Cleanup. Change "Core" to "Specialization Settings", label is more intuitive especially for English Second Language users. Stop using "normal" width and start using "1.5" width on stuff to create consistency, this is a parameter value you already use elsewhere, may as well stick with it.

image

**Comment by syrifgit** [comment]
Closing to split this PR into 2 parts, as well as cutting out what you've already done.

**Pull request closed without merging**
