### PR TITLE
Enhancements and Optimizations for Warrior Fury Profile

### PR DESCRIPTION
**Pull request by joshjau**
This pull request introduces several improvements to the Warrior Fury simulation profile, focusing on combat actions, cooldown management, trinket usage, action list refinements, and variable management.

1. Precombat Enhancements:
Added battle_shout and berserker_stance to pre-combat actions for a better initial setup.
Introduced variables to manage trinket exclusions and synchronize them based on cooldowns.

2. Cooldown Management:
Implemented pummel, charge, and heroic_leap with specific conditions to optimize movement and interrupt capabilities.
Added potion usage and racial abilities like lights_judgment and bag_of_tricks under certain conditions.
Enhanced the usage conditions for recklessness and avatar to better align with different fight phases.

3. Trinket Usage Optimization:
Improved trinket logic by prioritizing those with the highest estimated value and pairing them with Avatar.
Added conditions to handle trinket usage when only one provides a buff or when neither does.

4. Action List Refinements:
Refined single-target and multi-target rotations for both Slayer and Thane specializations to ensure optimal ability usage.
Adjusted conditions for abilities like recklessness, avatar, and bladestorm to maximize damage output.

5. Variable Management:
Introduced new variables for strategic planning, such as st_planning, adds_remain, and execute_phase.
Enhanced the on_gcd_racials variable to manage global cooldown racial abilities more effectively.

I believe these updates will enhance the Warrior Fury simulation's performance and accuracy, making it reflect in-game scenarios more precisely. I'd really appreciate it if you could review these changes and let me know your thoughts!

### CODE REVIEW

**Comment by syrifgit** [comment]
> Action List Refinements:
Refined single-target and multi-target rotations for both Slayer and Thane specializations to ensure optimal ability usage.
Adjusted conditions for abilities like recklessness, avatar, and bladestorm to maximize damage output.

Did you sim these changes to ensure it's actually a DPS increase compared to the sims?

I added some other comments, will let Hek look at the rest.

But if the changes are approved, you will need to update the pack string as well in the fury .lua file.

**Comment by Hekili** [comment]
> Did you sim these changes to ensure it's actually a DPS increase compared to the sims?

This is essential. Please provide some baseline sims from typical builds and then update them to use your revised APL. These do sound like potential improvements, but I try to avoid deviation from sim profiles without evidence.

**Review by joshjau — COMMENTED** [review]
fix a typo.

**Comment by joshjau** [comment]
> > Did you sim these changes to ensure it's actually a DPS increase compared to the sims?
> 
> This is essential. Please provide some baseline sims from typical builds and then update them to use your revised APL. These do sound like potential improvements, but I try to avoid deviation from sim profiles without evidence.

Ok, i should of added a fair bit more into the details and sims. You can close this off I may re-open soonish with all my ducks in a row. I added a quick fix to a typo in arms.simc as well.

**Pull request closed without merging**
