### PR TITLE
Update ReflectableSpells.lua with Nerub'ar Palace data and optimizations

### PR DESCRIPTION
**Pull request by joshjau**
- Added reflectable spells for Nerub'ar Palace Raid (A few missing still)
- Optimized data structures for improved performance
- Implemented caching system for spell info
- Added utility functions for spell reflection checks
- Improved error handling and logging
- Added comments for better code readability and maintenance

Note to Hekili:
These optimizations represent my initial effort to enhance the addon's performance. If these changes prove problematic or incompatible with other parts of your addon, please feel free to close this ticket. I can alternatively add the Nerub'ar Palace spell IDs to the original file structure without any optimization attempts if preferred.

### CODE REVIEW

**Comment by Hekili** [comment]
Is stripping spell names from the table in favor of `true` necessary to the optimization?  If so, I'd like to keep those names as comments for readability's sake.

**Comment by johnnylam88** [comment]
What numbers do you have to show that this actually improves the addon's performance? Do you have snapshots before and after your changes that show the improvement in the time needed to generate recommendations?

**Comment by johnnylam88** [comment]
Just to move this PR along, I think you're better off just adding the Nerubar Palace spells to the current data structure.

For the rest of the changes, you really need to show some sort of profiling or benchmarks that shows that the optimizations you're proposing are actually beneficial due to the extra complexity from the indirection layer you're adding.

**Comment by Hekili** [comment]
I added the Nerub'ar Palace auras using the existing format.

**Pull request closed without merging**
