### PR TITLE
[Cataclysm] Update and Fix Feral Druid

### PR DESCRIPTION
**Pull request by SergioRt1**
Changes:

* Clip Roar: Added missing functionality to clip roar.
* Berserk Expected At: Aligned with updated WoWSims implementation. https://github.com/wowsims/cata/pull/205
* Update Auras: Corrected outdated WotLK values to Cataclysm values.
* Bite DPE: Calculated Bite DPE; further adjustments needed.
* Rip Tick Damage: Calculated Rip tick damage; further adjustments needed.
* Clearcasting on Maul: Avoid using Clearcasting on Maul during bearweaving; use in cat form instead.

### CODE REVIEW

**Comment by Supernuss** [comment]
@Hekili Some, but not all of these changes are also in https://github.com/Hekili/hekili/pull/3298. 
I'm not sure if @SergioRt1 based his changes on my branch, if not we will probably get merge conflicts/duplicates when his PR goes before mine, since we changed similar parts.

**Comment by SergioRt1** [comment]
Oh, I didn't notice. My implementation was done independently, based on the WoWSims code.
@Supernuss Would you like me to pull the changes from your branch to resolve any conflicts and redirect this to your branch?

**Comment by Supernuss** [comment]
No Idea how Hekili wants to proceed. It would be great if he'd merge my PR so I could stop working over multiple Branches.^^ 
If you'd merge your code into my cata_dk branch I'd also include it in my pre-releases that most (casual players) are using for cata for now. It would also be automatically merged here as long as my PR is still open.
@Hekili is currently working on TWW beta, so he'd probably don't have time to review my larger pull requests - least thats what I tell myself :D

Feel free to proceed how you like, I'm open to merging it at a later time if needed - appreciate all work done on Cata 👍

**Comment by SergioRt1** [comment]
Moved to https://github.com/Supernuss/hekili/pull/26

**Pull request closed without merging**
