### PR TITLE
Disc Rotation

### PR DESCRIPTION
**Pull request by Nmxsz**
i made my own simple disc rotation tracking atonement buff on players in my group/raid to calculate when to ramp etc

### CODE REVIEW

**Review by Hekili — COMMENTED** [review]
I'm going to quickly allow this since it largely relates to the unsupported modules, so it is more or less sandboxed.

**Comment by Glorificuss** [comment]
can anyone help me load what he created? I can't seem to get Hekili to let me import it

**Comment by Nmxsz** [comment]
> can anyone help me load what he created? I can't seem to get Hekili to let me import it

I just created some methods for me to create my own heal/dps rotation.

I can Share my own rotation if u want to.

**Comment by Glorificuss** [comment]
that would be great!

**Comment by Nmxsz** [comment]
Ok to make it work you need to edit the file called "hekili.toc" in the addon folder of hekili. There u go to line 53 and remove the beginning "# " of "# Classes\PriestDiscipline.lua" so the spells cds from the disc priest can be loaded.

Then you need to import my rotation:
1)Start or reload WoW after editing the file above.
2) open hekili "/hekili"
3) go to "Priorities" and click "Share Priorities"
4) paste my import string 
5) accept and click "import Priority"
6) click "apply changes"

if you have any question u can add me ingame battle-tag Nmxsz#2843

Import String:
dy0SzaqijjAtevHgfkHtHsYQKkk9kIQuZIOk4wev2fQmmqfhtsTmqvpJOutdLORjjPTHsQ(MKegNKuohkPSoPIu9oPIuMhrj3tQq7tQGfIsnrqLYgjQs(iOs1ijQkoPurSsqLyMsfvUPurv7Ki)eujnuPIIwkrvvpvvtfvDvPIcFvQiP3sufDxIQs7v5VszWu5WKwmkEmftgXLH2mi9zPsJgeNwLxljvZMWTPQ2TWVbgovz5i9CjMUORdkBxs8DPQXtuv58efRxQiX(P0RE87jAItcE4aFDn81WZbhzZs4HdRVpLXd37PMQRDX9H6J7LpOkSo42vm79uzeaLm(9famQb3VNb2jYojgZEIM4KGhoWxxdFn8CWbEzx19fp0mj4RkRVhYriymM9eSy2Zd5kw3vSo168ut11UO1bGADQjpqyDIRKfRdkGADYhS6N4427rbqpbUxn5bIo6b6rARhqjTcKdfK9vqA5aXKGhoWxxdFn8CWbEzx199knUOBzppKRyDEua0tGw3vSo)RuUOR1vG55bOP1bfqTUUyG0ZyDj9IQJzHZ6SUojTURyDu0a89XGGeRlHOP1HvqQmwNh9a0lLX6UWiGrWI1HxcbPD6w4I1jN1jp7mkO11jj6xKVYdwxpKZaX6UWiGrWI1PHmwxsVO6ywSUaKwhk)8eN5sHmw3fgbmcsSUlSUecADE0dqVuMonRdqTWfRtoRtEYtVO6yAD1YxRtdI1jp5PxuDmTo4LVYdwxpKZaX66pHW6OOb47JbX6siO1L0lQoMwhua16siO1fW8zqksSUIaKCw4IeW6utEGW6exjlwxpsrR789a0ejwhukW36sixX68OaONa5SWL9IRKLXVV4RcrJQ(EJFs1JFpgkJajJ9E1Khi2xGOeqp0ddYEd9sKE6(Ltc(XpP6XVCpgkJajJ9E1Khi27b6rARhqjnQsonm4Yjj7XpP6XVCpgkJajJ9E1Khi2x8o6LTceui2BOxI0t3NQaJKR4D0lBfiOqWHHYiqYYjXYXpP6XVCpgkJajJ9E1Khi2Jv0OlkUI)Ed9sKE6(ufyKCyfn6IIR4ZHHYiqYYjv1XpP6XVCpgkJajJ9E1Khi2xmqUI)YjX6JFs1JF5Emugbsg79QjpqS3ddnm4YjvfJFs1JF5Emugbsg79QjpqS3d0J0wpGsAfGqn4YjvTXpP6XVCVAYde79VG0yeAj3JHYiqYyVCsS24Nu94xUhdLrGKXEVAYde7l(xIlxUNGqvyIC8tQE8tQE8l3BuV8aXE5KtoRdU6LhikwNCYj3E1Khi2xrPNYiW9eSyONxEGyVCYjN1bx9YdefRto5KBpgkJajJ9Yjb)4Nu94xUhdLrGKXEFfL2c1h3tvYPHbBAcc0hJS5FLYfD3RM8aX(kk9ugbUVIkGH7L9Yjj7XpP6XVCpgkJajJ9E1Khi2xrPNYiW9vuAluFCV)fnpm0WGTuPDXSSVIkGH7R3BOxI0t3VCsSC8tQE8l3JHYiqYyVVIsBH6J79VOPjiqFmY9QjpqSVIspLrG7ROcy4(QTCsvD8tQE8l3JHYiqYyV3OE5bI9YjNCwhC1lpquSomiwNCYj3Ecwm0ZlpqSxo5KZ6GRE5bII1HbX6Kto52RM8aX(kk9ugbUCsS(4Nu94xUhdLrGKXEVAYde7RO0tze4(kQagUxEDbPZb6LpEDMcvgK2PEjeaSKnmOqzltNa3yrnRXszxnwYQ9vubmSHIcUho7RO0wO(4EpHkdsB9xcbalBmWGcD5KQIXpP6XVCpgkJajJ9E1Khi2xrPNYiW9vuAluFCVMGa9XiBu0xVOSVIkGHnuuW9WzFfvad3lVUGi)1JWgguODoqpws5p6RxuyltNa3yrnRXszxnwYQLtQAJFs1JF5Emugbsg79QjpqSVIspLrG7ROcy4E51fe5VEe2WGcLTmDcCJf1SglLD1yjR2xrfWWgkk4E4SVIsBH6J71eeOpgzZaGf5YjXAJFs1JF5Emugbsg79QjpqSVIspLrG7ROcy4(9g6Li909WDmLG5d3PayEDE0NbPfwWkRRdwhCSoniwhl0eeOpgzZaGfP11HoAD(x00eeOpgP1PbX60eeOpgzJI(6ffRtwDKLSY6auRJbguOCfVJEzRabfcoyEwhGADmWGcLJbaIgaAlHGnTyWGGeoyE7RO0wO(4EQ6718GOfC5KQHZ4Nu94xUhdLrGKXEVAYde7nQq0utEGOjUsU3qVePNUpvbgjxX7Ox2kqqHGddLrGeRtdI1XcdaiiG(GR4D0lBfiOqWrrLiJ1bOwhdmOq5kEh9YwbckeCW8yL1PbX6OQVxZdIwqRtdI1XcdaiiG(GJbaIgaAlHGnTyWGGeokQezSoa16yGbfkhdaena0wcbBAXGbbjCW8y1EXvYwO(4EQ671kEh9YwbckelNuD94Nu94xUhdLrGKXEVAYde7nQq0utEGOjUsU3qVePNUpvbgjhwrJUO4k(CyOmcKyDAqSoQ6718GOf060GyDSWaaccOp4yaGObG2siytlgmiiHJIkrgRdqTogyqHYXaardaTLqWMwmyqqchmpwzDAqSodaiiG(GdROrxuCfFokQezSoa16maGGa6doSIgDrXv85OOVErX66qhTUQao7fxjBH6J7PQVxdROrxuCf)LtQg(XpP6XVCpgkJajJ9E1Khi2BuHOPM8artCLCVHEjspDpChtjy(WDkaMxNh9zqAHfSY66qvToniwhlmaGGa6dUI3rVSvGGcbhfvImwhGADmWGcLR4D0lBfiOqWbZJvwNgeRZaaccOp4WkA0ffxXNJIkrgRtdI1rvFVMheTGwNgeRRknaGGa6dogaiAaOTec20Ibdcs4OOsKX60GyDvjdmOq5yaGObG2siytlgmiiHdM3EXvYwO(4(IVkenQ67TCs1YE8tQE8l3JHYiqYyVxn5bI9EGEK26busJQKtddU3qVePNUNfmWGcLJbaIgaAlHGnTyWGGeoyEwNgeRJbguOCmaq0aqBjeSPfdgeKWrrF9II1jlRd(oBxdX6K3wxnRSoniwNNqLbPT(lHaGLngyqHADDOJ1lNunlh)KQh)Y9yOmcKm27vtEGyVwmyqqsJrOLCVHEjspDpdmOq5yaGObG2siytlgmiiHdM3Yjvx1XpP6XVCpgkJajJ9E1Khi2RfdgeK0cqfDVHEjspDpdmOq5yaGObG2siytlgmiiHdMN1PbX6sL2ftoYvsnmO1jRoADvB5KQz9XpP6XVCpgkJajJ9Ed9sKE6EkcLIfikJaTo5rRlvAxm5YZhBjOro066G1XY9QjpqS3dgTl2siyR)mvhj7nYyeylvAxmltQE5KQRIXpP6XVCpgkJajJ9E1Khi27bJ2fBjeS1FMQJK9g6Li909vP1LNP6x0DVrgJaBPs7Izzs1lNuD1g)KQh)Y9yOmcKm27vtEGyVhOhPTEaL0Ok50WG7n0lr6P79eQmiT1FjeaSSXadkuRRdDKQKtdd20eeOpgzZ)kLl6ADAqSowyaabb0hCEGEK26busJQKtddYzGO0UyX66G1bhRtdI1XcdaiiG(GZd0J0wpGsAuLCAyqok6RxuSo5T1bpCSozzDgaqqa9bxX7Ox2kqqHGJI(6ffRtdI1LQaJKR4D0lBfiOqWHHYiqcRSoa16yHbaeeqFW5b6rARhqjnQsonmihf91lkwN826GhowNSSodaiiG(GdROrxuCfFok6RxuSoniwxQcmsoSIgDrXv85WqzeiHvwhGADPkWi5eyCyyqomugbsy1YjvZAJFs1JF5Emugbsg79QjpqSVyGCf)9g6Li909SWaaccOp4kgixXNJI(6ffRtwwNbaeeqFWv8o6LTceui4OOVErHvwhGADSWaaccOp4kgixXNJI(6ffRtwwNbaeeqFWHv0OlkUIphf91lkSA5KGhoJFs1JF5Emugbsg79QjpqS3ddnm4Ed9sKE6Enbb6Jr2mayrADDOJwN)fnpm0WGTuPDXSyDAqSonbb6Jr2OOVErX66G1PM8abNhgAyqou(Hgyj2YZhTUoR111qwoj4Rh)KQh)Y9yOmcKm27vtEGyV)fKgJql5Ed9sKE6(LtcE4h)KQh)Y9yOmcKm27vtEGyVhOhPTEaL0kaHAW9g6Li909lNe8YE8tQE8l3RM8aX(I)L4Emugbsg7LtcEwo(jvp(L7XqzeizS3RM8aXEQ6LWO4Ed9sKE6(ufyKCcmommihgkJajwhGADPkWi5WkA0ffxXNddLrGKLtc(Qo(jvp(L7XqzeizS3RM8aXEpqpsB9akPvGCOGS3qVePNUNbguOCu1lHrroyElxU3JIgGpJMJFs1JFVAYde79a9iT1dOKwbYHcYEmugbsgZYL7PQVxR4D0lBfiOqm(jvp(jvp(L7XqzeizS3RM8aX(I3rVSvGGcXEd9sKE6EgyqHYXaardaTLqWMwmyqqchmpRtdI1LQaJKR4D0lBfiOqWHHYiqYYjb)4Nu94xUhdLrGKXEVAYde7zaGObG2siytlgmiizVHEjspDVbaeeqFW5b6rARhqjnQsonmiNbIs7IfRtwwh8lNKSh)KQh)Y9yOmcKm27vtEGypwrJUO4k(7n0lr6P7tvGrYHv0OlkUIphgkJajwNgeRttqG(yKnk6RxuSoz1rRJLCv160GyDAcc0hJSrrF9II11bRR260GyDgaqqa9bNhOhPTEaL0Ok50WGCgikTlwSozzD1lNelh)KQh)Y9yOmcKm27vtEGyVhOhPTEaL0Ok50WG7n0lr6P7naGGa6dUceLa6HEyq4OOsKz5KQ64Nu94xUhdLrGKXEVAYde7lgixXFVHEjspDVbaeeqFW5b6rARhqjnQsonmiNbIs7IfRtwwxT1PbX6QsdaiiG(GtlgmiiPXi0sYrrLiZYjX6JFs1JF5E1Khi2RfdgeK0yeAj3JHYiqYyVCsvX4Nu94xUhdLrGKXEVAYde71IbdcsAbOIU3qVePNUpvAxm5ixj1WGwNS6O1vTLtQAJFs1JF5Emugbsg79QjpqS3d0J0wpGsAuLCAyW9g6Li909mWGcLJbaIgaAlHGnTyWGGeoyEwNgeRJbguOCfVJEzRabfcoyEwNgeRRknaGGa6doTyWGGKgJqljhfvImlNeRn(jvp(L7XqzeizS3RM8aXEpm0WGlNunCg)KQh)Y9yOmcKm27vtEGyV)fKgJql5Yjvxp(jvp(L7XqzeizS3RM8aXEpqpsB9akPvac1GlxUNQ(EnSIgDrXv8h)KQh)KQh)Y9yOmcKm27vtEGyVhOhPTEaL0Ok50WGlNe8JFpgkJajJ9E1Khi2Jv0OlkUI)Ed9sKE6(ufyKCyfn6IIR4ZHHYiqYYjj7XpP6XVCpgkJajJ9E1Khi2ZaardaTLqWMwmyqqYYjXYXpP6XVCpgkJajJ9E1Khi2xmqUI)Ed9sKE6EgyqHYXaardaTLqWMwmyqqchmpRtdI1vLgaqqa9bNwmyqqsJrOLKJIkrMLtQQJFs1JF5Emugbsg79QjpqSxlgmiiPXi0sUCsS(4Nu94xUhdLrGKXEVAYde71IbdcsAbOIU3qVePNUpvAxm5ixj1WGwNS6O1vTLtQkg)KQh)Y9yOmcKm27vtEGyVhOhPTEaL0kaHAWLlxUxHLqa09s(YVsNYYLBa

**Comment by Nmxsz** [comment]
there are also some options you can set:
https://imgur.com/a/dJ9yp7X

1) variable "radiance_atonement_missing" is set to 3 which means if 3 people have no atonement buffed and are below 80% hp then PW:R will be suggested
2) variable "min_penance_targets" is set to 1 that means that atleast 1 people should have an atonement buff for penance to be suggested
3) variable "min_atonement" is set to 8 and its based on a 20 man raid with my low haste rating. That variable triggers the ramp phases so when u apply 8 atonement to the raid the roation will trigger a ramp phase based on your talents spirit shell or evangelism. 

Theres also a standard function to get the current group members its called "GetNumGroupMembers()" and with this function its possible to set the variable dynamically like "GetNumGroupMembers() / 2" or something like this

every option can be modified

**Pull request merged**
